app = "mozika-app"
primary_region = "cdg"

[build]
  image = "node:18"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
[env]
  PORT = "8080"
[deploy]
  strategy = "immediate"
